services:
  db:
    image: postgres:18
    container_name: linux-monitoring-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: linux-monitoring-django:latest
    container_name: linux-monitoring-django
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.local
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: