# Generated by Django 6.0.7 on 2026-08-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='servers.server')),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'metric_name', 'timestamp'], name='monitoring__server__f61617_idx')],
            },
        ),
    ]
