# Generated by Django 6.0.7 on 2026-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsample',
            name='metric_name',
            field=models.CharField(max_length=255),
        ),
    ]
