# Generated by Django 6.0.7 on 2026-08-05 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(help_text='Human-readable name of the server.', max_length=100)),
                ('hostname', models.CharField(help_text='Hostname or IP address of the server.', max_length=255, unique=True)),
                ('ssh_port', models.PositiveIntegerField(default=22, help_text='SSH port number.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('username', models.CharField(help_text='Username used for SSH authentication.', max_length=100)),
                ('password', models.CharField(help_text='Password used for SSH authentication.', max_length=255)),
                ('operating_system', models.CharField(choices=[('UBUNTU', 'Ubuntu'), ('DEBIAN', 'Debian'), ('CENTOS', 'CentOS'), ('ROCKY', 'Rocky Linux'), ('AMAZON', 'Amazon Linux')], default='UBUNTU', help_text='Operating system running on the server.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional notes about the server.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether monitoring is enabled for this server.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
