# Generated by Django 6.0.7 on 2026-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_check_at',
            field=models.DateTimeField(blank=True, help_text='When monitoring was last attempted.', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_error',
            field=models.TextField(blank=True, default='', help_text='Error from the latest failed monitoring attempt.'),
        ),
        migrations.AddField(
            model_name='server',
            name='last_success_at',
            field=models.DateTimeField(blank=True, help_text='When monitoring last succeeded.', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('UP', 'Up'), ('DOWN', 'Down')], default='UNKNOWN', help_text='Current monitoring status of the server.', max_length=10),
        ),
    ]
