# Generated by Django 6.0.7 on 2026-09-12 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_last_check_at_server_last_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Summary of the alert issue.', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Detailed alert description or diagnostic log.')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', help_text='Severity level of the alert.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', help_text='Current state of the alert.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the alert was marked resolved.', null=True)),
                ('server', models.ForeignKey(help_text='The server associated with this alert.', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='servers.server')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
