# Generated by Django 6.0.7 on 2026-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OPERATOR', 'Operator'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='User role determining system permissions (Admin, Operator, Viewer).', max_length=20, verbose_name='Role'),
        ),
    ]
